# Generated by Django 6.0.5 on 2026-05-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dining_option',
            field=models.CharField(default='', max_length=20),
        ),
    ]
