# Generated by Django 6.0.5 on 2026-05-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_userprofile_dining_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
