# Generated by Django 6.0.5 on 2026-05-31 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_userprofile_security_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='security_answer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='security_question',
        ),
    ]
