# Generated by Django 6.0.5 on 2026-05-31 07:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_userprofile_security_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='mobile',
        ),
        migrations.AddField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(default='temp@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
