# Generated by Django 6.0.5 on 2026-06-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_otp_mobile_otp_created_at_otp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='Occupied', max_length=20),
        ),
    ]
