# Generated by Django 6.0.5 on 2026-06-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Occupied', 'Occupied'), ('Available', 'Available')], default='Occupied', max_length=20),
        ),
    ]
